FROM nvidia/cuda:12.1.1-cudnn8-devel-ubuntu20.04
WORKDIR /root
ARG DEBIAN_FRONTEND=noninteractive
ENV TORCH_CUDA_ARCH_LIST="7.0 7.5 8.0"

RUN apt-get -y update
RUN apt install -y software-properties-common
RUN apt-get install -y vim wget git curl
RUN apt install -y libjpeg-dev zlib1g-dev

RUN apt -y install build-essential libssl-dev
RUN wget https://github.com/Kitware/CMake/releases/download/v3.19.6/cmake-3.19.6.tar.gz
RUN tar -zxvf cmake-3.19.6.tar.gz
RUN cd cmake-3.19.6 && ./bootstrap && make && make install && cp bin/cmake /bin/  && cd ..

RUN apt update -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt install python3.10-dev -y

RUN apt-get -y install python3-pip
RUN apt -y install python3.10-distutils
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
RUN python3.10 -m pip install --upgrade pip
RUN python3.10 -m pip install pyyaml typing_extensions
RUN python3.10 -m pip install Pillow
RUN python3.10 -m pip install numpy
RUN python3.10 -m pip install pandas
RUN python3.10 -m pip install mpmath==1.3.0

RUN git clone --recursive https://github.com/pytorch/pytorch
RUN cd pytorch && git reset --hard 7bcf7da3a268b435777fe87c7794c382f444e86d && git submodule sync && git submodule update --init --recursive --jobs 0 && python3.10 setup.py develop && cd ..

RUN git clone https://github.com/pytorch/vision.git
RUN cd vision && git reset --hard fbb4cc54ed521ba912f50f180dc16a213775bf5c && python3.10 setup.py develop && cd ..

RUN echo "alias python=python3.10" >> /root/.bashrc
SHELL ["source" , "/root/.bashrc"]
SHELL ["/bin/sh", "-c"]
